### testing profiles API
POST http://localhost:5000/password/reset/code
Content-Type: application/json

{
	"email": "nasandratra.access4@gmail.com"
}

### resetting password
POST http://localhost:5000/password/reset
Content-Type: application/json

{
	"email": "nasandratra.access4@gmail.com",
	"code": "O7OG54",
	"newPassword": "newSecurePassword123",
	"confirmPassword": "newSecurePassword123"
}